package com.risutoken.tokenizer

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource
import java.nio.file.Path
import kotlin.io.path.Path
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Correctness gate: Java engines must produce EXACTLY the same token ids as
 * RisuAI's WASM libs (@dqbd/tiktoken + @mlc-ai/web-tokenizers).
 *
 * Fixtures are generated by server-node/scripts/generate-golden.mjs against the
 * same model files RisuAI ships in public/token/.
 */
class GoldenCompatibilityTest {

    data class Case(val tokenizer: String, val text: String, val ids: List<Int>)

    private val modelsDir: Path = Path(System.getProperty("user.dir")).parent.resolve("models")
    private val goldenDir: Path = Path(System.getProperty("user.dir"))
        .resolve("src/test/resources/golden")
    private val mapper = ObjectMapper()

    private fun loadCases(file: String): List<Case> {
        val node = mapper.readTree(goldenDir.resolve(file).toFile())
        return node.map { c ->
            Case(
                tokenizer = c["tokenizer"].asText(),
                text = c["text"].asText(),
                ids = c["ids"].map { it.asInt() },
            )
        }
    }

    private fun engineFor(name: String): TokenizerEngine = when (name) {
        "cl100k_base" -> JtokkitEngine.cl100kBase()
        "o200k_base" -> JtokkitEngine.o200kBase()
        "llama3", "claude", "deepseek" ->
            DjlEngine.fromJson(name, modelsDir.resolve("$name.json"))
        else -> error("unknown tokenizer $name")
    }

    @ParameterizedTest
    @MethodSource("tokenizerNames")
    fun `ids match RisuAI WASM reference`(name: String) {
        val cases = loadCases("$name.json")
        assertTrue(cases.isNotEmpty(), "golden fixture must exist for $name")
        val engine = engineFor(name)
        for (c in cases) {
            val actual = engine.encode(c.text).toList()
            assertEquals(
                c.ids, actual,
                "token mismatch for tokenizer=$name text=${c.text.take(40)}",
            )
        }
    }

    companion object {
        @JvmStatic
        fun tokenizerNames(): List<String> =
            listOf("cl100k_base", "o200k_base", "llama3", "claude", "deepseek")
    }
}
